# Access to host network is required to send WOL magic packets
controllers:
  main:
    containers:
      main:
        dependsOn: 
          - postgres
          - redis
        image:
          # -- image repository
          repository: docker.io/ghostfolio/ghostfolio
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: latest
        env:
          DATABASE_URL: 'postgresql://{{ postgresql.auth.username }}:${{ postgresql.auth.password }}@postgres:5432/{{ postgresql.auth.database }}?connect_timeout=300&sslmode=prefer'
          REDIS_HOST: redis
          REDIS_PASSWORD: '{{ .Release.Name }}'

ghostfolio: #
  nodeEnv: production
  accessTokenSalt: sometokensometokenso
  jwtSecretKey: sometokensometokenso

postgresql: #
  enabled: true
  primary:
    persistence:
      size: 2Gi
  image:
    tag: 15.4.0
  auth:
    postgresPassword: changeme
    username: ghostfolio
    password: changeme
    database: ghostfolio

redis: #
  enabled: true
  master:
    persistence:
      enabled: false
  architecture: standalone
  auth:
    password: changeme

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 3333

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
    # ingressClassName: "traefik"
    # annotations: []
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         service:
    #           identifier: main
    #           port: http
