controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: recyclarr/recyclarr
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: latest
      code:
        dependsOn: main
        image:
          # -- image repository
          repository: ghcr.io/coder/code-server
          # -- image tag
          # this example is not automatically updated, so be sure to use the latest image
          tag: 4.92.2
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
          - --port
          - "8081"
          - "/config"
service:
  # Configure a service for the code-server sidecar
  code:
    type: ClusterIP
    controller: main
    ports:
      http:
        port: 8081
persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config