controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: recyclarr/recyclarr
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: latest
persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config