# Access to host network is required to send WOL magic packets
defaultPodOptions:
  hostNetwork: true

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: docker.io/jellyfin/jellyfin
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: latest

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 8096
# environment:
#   - SOMETHING=https://my-domain.com

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
    # ingressClassName: "traefik"
    # annotations: []
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         service:
    #           identifier: main
    #           port: http
persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config
