controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: syncthing/syncthing
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 1.27.9

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 8384

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
    # ingressClassName: "traefik"
    # annotations: []
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         service:
    #           identifier: main
    #           port: http
persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /var/syncthing