controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: golift/notifiarr
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 0.8.1

# see https://hub.docker.com/r/golift/notifiarr
# for a complete list of options
# environment:
#   - DN_API_KEY=XXXXXXXXXXXXXX
#   - DN_AUTO_UPDATE=off
#   - DN_BIND_ADDR=0.0.0.0:5454
#   - DN_QUIET=false
#   - DN_UI_PASSWORD=XXXXXXXXXXXXXX

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 5454

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
    # ingressClassName: "traefik"
    # annotations: []
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         service:
    #           identifier: main
    #           port: http
persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config