controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: rclone/rclone
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 1.67.0
          args:
            - rcd
            - --rc-addr=:5572
            - --rc-web-gui
            - --rc-web-gui-no-open-browser
            # - --rc-user=xxxxx
            # - --rc-pass=xxxxx

# -- Configures service settings for the chart.
service:
  main:
    controller: main
    ports:
      http:
        port: 5572

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  main:
    enabled: false
    # ingressClassName: "traefik"
    # annotations: []
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         service:
    #           identifier: main
    #           port: http
persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config