apiVersion: v1
kind: Secret
metadata:
  name: ghostfolio-secret
type: Opaque
data:
  accessTokenSalt: {{ .Values.ghostfolio.accessTokenSalt | b64enc | quote }} #
  jwtSecretKey: {{ .Values.ghostfolio.jwtSecretKey | b64enc | quote }}
  {{- with .Values.postgresql.auth }} #
  postgresqlUrl: {{ printf "postgresql://%s:%s@ghostfolio-postgresql:5432/%s?sslmode=prefer" .username .password .database | b64enc | quote }}
  {{- end -}}